= Kafka and Ranger on a Kerberized HDP 3.x Cluster
<venky@cloudera.com>
v0.1, 2019-08-22: draft
:page-layout: docs
:description: How-to work with Kafka on a Ranger Enabled Kerberized HDP Cluster
:icons: font
:uri-fontawesome: https://fontawesome.com/v4.7.0/
:imagesdir: ./images
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

=== Intro
Steps to work with Kafka when you have a Ranger enabled kerberized HDP 3.x cluster. 

=== Assumptions
Using `SASL_PLAINTEXT` security module for Kafka.

=== Pre-Requisites
Installation of components is assumed. A useable AMI under the HWX AWS account in Oregon Region: `ami-0695d746d0b40fdaf`.

=== Steps
. Create topic as kafka service user.
. Using kafka acl's, allow specific user to access a topic as a producer.
. Using kafka acl's, allow specific user to consume data from a topic as a consumer.
. Modify Ranger permissions to allow user to have access to kafka.

=== Sanity Check
.. Map the AWS IP address to `hdp31.cloudera.com` in your /etc/hosts.
... This instance is knox-enabled, so use incognito or firefox else redirects take place.
.. Check ambari at 8080, `https://hdp31.cloudera.com:8080` login as `admin/BadPass#1`
.. The default login user is `centos` and the service user is `etl_user`.
.. Check that services are up.
.. Login in the usual way.
+
[source,bash]
----
ssh -i <.pem> -l centos <IPAddress>
----

=== How-To
. Create Topic 
.. Best practice is to create this as `kafka` service user.
+
[source,bash]
----
sudo su - kafka

klist -kte /etc/security/keytabs/kafka.service.keytab

kinit -Vkt /etc/security/keytabs/kafka.service.keytab kafka/$(hostname -f)@HWXDR.COM

/usr/hdp/current/kafka-broker/bin/kafka-topics.sh --zookeeper $(hostname -f):2181 --list

/usr/hdp/current/kafka-broker/bin/kafka-topics.sh --zookeeper $(hostname -f):2181 --create --topic zzzfoo --partitions 1 --replication-factor 1
Created topic "zzzfoo"
----

. Apply Kafka ACL's for Producer, for user `etl_user` on topic `zzzfoo`
+
[source,bash]
----
/usr/hdp/current/kafka-broker/bin/kafka-acls.sh --authorizer-properties zookeeper.connect=$(hostname -f) --add --allow-principal User:etl_user --producer --topic zzzfoo
----

. Apply Kafka ACL's for Consumer, for user `etl_user` on topic `zzzfoo` belonging to any group.

+
[source,bash]
----
/usr/hdp/current/kafka-broker/bin/kafka-acls.sh --authorizer-properties zookeeper.connect=$(hostname -f) --add --allow-principal User:etl_user --consumer --topic zzzfoo --group *
----

. Test
.. Login as `etl_user`.
+
[source,bash]
----
sudo su - etl_user

kinit -Vkt /etc/security/keytabs/etl_user.keytab etl_user/$(hostname -f)@HWXDR.COM
----

.. Open 2 terminal windows , one for producer and one for consumer.
+
[source, bash]
----
/usr/hdp/current/kafka-broker/bin/kafka-console-producer.sh --broker-list $(hostname -f):6667 --topic zzzfoo --producer-property security.protocol=SASL_PLAINTEXT
----

.. Consumer
+
[source, bash]
----
/usr/hdp/current/kafka-broker/bin/kafka-console-consumer.sh --bootstrap-server $(hostname -f):6667 --topic zzzfoo --consumer-property security.protocol=SASL_PLAINTEXT
----
... This should *fail*, as `etl_user` is not enabled for kafka by default.
... Go to Ranger UI at `http://hdp31.cloudera.com:6080`.
... Change the Ranger policy under Kafka to include the `etl` group or add `etl_user` as a valid user.
... Save and *restart* Kafka.

.. Send messages on Producer window and it should be visible on the Consumer side.

. Using Java Client for Kerberized Kafka
.. There are 5 properties that need to be set.
... System Property : java.security.krb5.conf
... System Property : java.security.auth.login.config
... Kafka Producer Property : security.protocol
... Kafka Producer Property :  
sasl.kerberos.service.name

.. Example for the AMI above
... System Property
+
[source,bash]
----

java.security.krb5.conf=/etc/krb5.conf
java.security.auth.login.config=/etc/kafka/3.1.0.0-78/0/kafka_client_jaas.conf
----
... Kafka specific property
+
[source,bash]
----
security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka
----

. Complete Java Example
.. TBD!